language: ruby
cache: bundler
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - 2.6.3
  - ruby-head
env:
  - DB=SQLITE
  - DB=POSTGRES
  - DB=MYSQL
addons:
  postgresql: "9.4"
services:
  - mysql
before_install:
  # https://github.com/travis-ci/travis-ci/issues/8978
  - "travis_retry gem update --system"
  # Rails 4.2 has a bundler 1.x requirement
  - if [ $BUNDLE_GEMFILE = $PWD/gemfiles/rails42.gemfile ]; then
      travis_retry gem install -v '1.17.3' bundler;
      bundle _1.17.3_ install;
    else
      travis_retry gem install bundler;
    fi
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile
  - gemfiles/rails60.gemfile
  - gemfiles/rails61.gemfile
matrix:
  include:
    - rvm: 2.6.3
      script: bundle exec rubocop --parallel
      env: DB=rubocop # make travis build display nicer
  exclude:
    - rvm: 2.3.7
      gemfile: gemfiles/rails61.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/rails61.gemfile
    - rvm: 2.3.7
      gemfile: gemfiles/rails60.gemfile
    - rvm: 2.4.4
      gemfile: gemfiles/rails60.gemfile
    - rvm: 2.6.3
      gemfile: gemfiles/rails42.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails42.gemfile
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
branches:
  only:
  - master
  - /.*-stable$/
notifications:
  webhooks:
    urls:
    - http://buildlight.collectiveidea.com/
    on_start: always
